# Generated by Django 2.2.24 on 2022-02-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rural_properties', '0002_auto_20220210_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruralproperty',
            name='owners',
            field=models.ManyToManyField(blank=True, null=True, related_name='RuralProperty', to='owners.LandOwner'),
        ),
    ]
