# Generated by Django 2.2.24 on 2022-02-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urban_properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urbanproperty',
            name='tipe',
            field=models.CharField(default='Urban', editable=False, max_length=5),
        ),
    ]
