# Generated by Django 2.2.24 on 2022-02-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urban_properties', '0003_auto_20220210_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urbanproperty',
            name='tipe',
            field=models.CharField(default='urban', editable=False, max_length=5),
        ),
    ]
