# Generated by Django 2.2.24 on 2022-02-10 14:14

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandOwner',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(8)])),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tipe_owner', models.CharField(choices=[('PERSON', 'person'), ('COMPANY', 'company')], editable=False, max_length=7)),
                ('names', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('country', models.CharField(default='Colombia', max_length=200)),
                ('department', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=300, unique=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Land Owners',
                'verbose_name_plural': 'Land Owners',
            },
        ),
    ]
