# Generated by Django 2.2.24 on 2022-02-10 14:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landowner',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
