# Generated by Django 2.2.24 on 2022-02-10 14:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0002_auto_20220210_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landowner',
            name='id',
        ),
        migrations.AddField(
            model_name='landowner',
            name='id_owner',
            field=models.IntegerField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='landowner',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='landowner',
            name='tipe_owner',
            field=models.CharField(choices=[('PERSON', 'person'), ('COMPANY', 'company')], max_length=7),
        ),
    ]
