# Generated by Django 2.2.24 on 2022-02-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0003_auto_20220210_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landowner',
            name='id_owner',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
