# Generated by Django 2.2.24 on 2022-02-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0004_auto_20220210_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landowner',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
